services:
  # VSCode web IDE
  vscode:
    image: linuxserver/openvscode-server
    container_name: vscode
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED # code-server
    environment:
      VIRTUAL_HOST: $DOMAIN
      LETSENCRYPT_HOST: $DOMAIN
      PUID: $PUID
      PGID: $PGID
      TZ: "Etc/UTC"
      SUDO_PASSWORD: $PASSWORD
      SUDO_USERNAME: $USERNAME
      CONNECTION_TOKEN: $CONNECTION_TOKEN
    volumes:
      - config:/config
      - ./workspace:/config/workspace # ton projet Nuxt

  # Conteneur Nuxt 3
  nuxt:
    image: node:20-bullseye
    container_name: nuxt
    restart: unless-stopped
    working_dir: /workspace
    command: sh -c "pnpm install && pnpm dev --host 0.0.0.0 --port 3000"
    environment:
      VIRTUAL_HOST: $DOMAIN_NUXT
      LETSENCRYPT_HOST: $DOMAIN_NUXT
      NODE_ENV: development
    ports:
      - $PORT_EXPOSED:$PORT_EXPOSED
    volumes:
      - ./workspace:/workspace
      - nuxt-node-modules:/workspace/node_modules
    depends_on:
      - vscode

volumes:
  config:
  nuxt-node-modules:

networks:
  default:
    name: dockerweb
    external: true
